name: Update events from PMB

on:
  workflow_dispatch:  # Manuell auslösbar

jobs:
  download-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create data directory if it doesn't exist
        run: mkdir -p data

      - name: Download XML file
        run: curl -o data/listevent.xml https://pmb.acdh.oeaw.ac.at/media/listevent.xml

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/editions/listevent.xml
          git commit -m "Automatisch heruntergeladene listevent.xml" || echo "Keine Änderungen zu committen"
          git push
