name: Update events from PMB

on:
  workflow_dispatch:  # Manuell auslösbar

jobs:
  download-transform-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Java (required for Saxon)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies (falls benötigt)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Download Saxon HE 10.8 (fat JAR)
        run: |
          mkdir saxon
          curl -L -o saxon/saxon-he.jar https://repo1.maven.org/maven2/net/sf/saxon/Saxon-HE/10.8/Saxon-HE-10.8.jar

      - name: Create data directory
        run: mkdir -p data/editions

      - name: Download original XML
        run: curl -o temp-listevent.xml https://pmb.acdh.oeaw.ac.at/media/listevent.xml

      - name: Transform XML with Saxon 10.8
        run: |
          java -jar saxon/saxon-he.jar \
            -s:temp-listevent.xml \
            -xsl:xslt/import-listevent.xsl \
            -o:data/editions/listevent.xml

      - name: Commit and push transformed XML
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/editions/listevent.xml
          git commit -m "Automatisch transformierte listevent.xml mit Saxon HE 10.8 aktualisiert" || echo "Keine Änderungen zu committen"
          git push

      - name: Run mentions-in-listevent.py
        run: python ./python/mentions-in-listevent.py

      - name: Run create-lists.py
        run: python ./python/create-lists.py

      - name: Commit and push indices
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/indices/*
          git commit -m "Automatisch generierte Indexdateien aktualisiert" || echo "Keine Änderungen zu committen"
          git push
